server:
  port: 3309

spring:
  application:
    name: movie

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "12345"
      database: 0
      timeout: 5000

  datasource:
    name: 'douyin'
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=GMT
    username: 'root'
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  main:
    allow-circular-references: true
#有点问题


mybatis-plus:
  type-aliases-package: com.bjtu.entity
  mapper-locations: classpath:/mappers/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# 监控
javamelody:
  enabled: true
  init-parameters:
    log: true

# 日志级别
logging:
  level:
    com.bjtu.douyin: debug